### ISSUE TITLE
test(s) for eventual send operator syntax?

### ISSUE THREAD

**Issue by dckc** [Agoric/SwingSet#150]
Why does this package depend on `@agoric/acorn-infix-bang`? In my work on xs (#126) I seem to be able to pass a bunch of tests without it. I guess I haven't worked on the demo tests yet, though...

https://github.com/Agoric/SwingSet/blob/38cd6b2d1e825d207a30b14f25e8e6f85b2b5b20/package.json#L41

**Comment by warner** [comment]
`test/test-demos-comms.js` builds Vats out of `demo/encouragementBotCommsBang/*.js`, which exercises infix-bang (`pbot!encourageMe('user')` instead of `E(pbot).encourageMe('user')`). At one point we were also doing this transform in the web frontend on cosmic-swingset, but I think it was removed from there.

It looks like `acorn-infix-bang` is used by `src/build-source-bundle.js`, which is used to turn Vat code modules into a single string, ready for delivery to the SES `evaluate` function.

**Comment by warner** [comment]
in the old repo. this was SwingSet issue 150
