### ISSUE TITLE
fix commsSlots outbound mapping

### ISSUE THREAD

**Issue by warner** [Agoric/SwingSet#79]
Agoric/cosmic-swingset#18 discovered that the commsSlots layer wasn't correctly handling a local object (kernel export, comms-vat import) that was made available to multiple external machines (machine egress).

The data structure is supposed to be a table per external machine (used when accepting references inside messages *from* that machine, or when translating our own references in a message *to* that machine). This table is a bidirectional mapping of the external-machine -facing reference (e.g. `your-egress-4`) to a kernel-facing reference (`import-6`).

Since our state is limited to things that can be stored in a flat key-value map (string-to-string), we represent the bidirectional mapping with a pair of unidirectional entries. The code relies upon the uniqueness of the type strings, and stores both entries in the same map.

The specific problem was that the outgoing direction of this map was using the kernel-facing reference as a key, rather than combining it with the remote machine name.

#78 changed this to fix the mapping,  but it also introduced an erroneous feature: the target of each outbound message is mapped to a *list* of remote targets, and sent to them all. I think I wasn't clear in my writeup, and implied that `commsVat.addEgress()` ought to let someone register the same object multiple times for the same remote machine (which should be an error), when I meant that `addEgress()` should allow the same object to be registered once-each for a number of different remote machines.

I expect that the current code will work as long as we don't take advantage of this property, but this ticket is about removing it and going back to one-egress-per-(object*machine).

**Comment by warner** [comment]
Also I think the `&&` in `CLists.js makeCLists() / checkIfAlreadyExists()` should go back to being a `||`:

```
    if (slot && outgoing) {
      throw new Error(`${kernelToMeKey} already exists in clist`);
    }
```

The table is supposed to be a bidirectional mapping: either both sides should be present, or neither.

**Comment by katelynsills** [comment]
Hi Brian, I'd like to better understand the requirements for SwingSet, and how our current implementation fails to meet those requirements. I'm ok if we choose to go with a particular data structure over what we have now, but if at all possible, I'd like to I understand why. 

I'd also like to ensure that if we move to a different data structure based on perceived problems, it's because we've accurately identified the problems. I think that some of the perceived problems listed above are inaccurate.

For instance, above you said:
> I think I wasn't clear in my writeup, and implied that commsVat.addEgress() ought to let someone register the same object multiple times for the same remote machine (which should be an error), when I meant that addEgress() should allow the same object to be registered once-each for a number of different remote machines.

My understanding was always that addEgress() should error if someone registers the same object multiple times for the same remote machine, so we are on the same page here. I made a test for this specific case on [this branch](https://github.com/Agoric/SwingSet/tree/test-same-addEgress-twice), and the test passes with no alternations, so I am really surprised to see this come up.

You're right that prior to Agoric/SwingSet#78, the cList implementation intentionally did not support the same kernel slot being mapped to multiple different machines. Because we've been moving fast, there are a number of features that still haven't be built, and I had a TODO to investigate further and left it at that. Since we hadn't had any tests with more than two machines, this feature never got built. But, with https://github.com/Agoric/cosmic-swingset/issues/18 it was clear that supporting multiple machines for the same kernelSlot was a priority, so I changed the CList implementation to support multiple machines in Agoric/SwingSet#78. 

I think Agoric/SwingSet#78 fits all of our requirements for SwingSet. If possible, I'd like to try to separate the requirements from the particular data structure used the fulfill the requirements, as long as it is equivalently efficient and safe. 

One of our requirements is that we need to be able to map the facetid that we get in `dispatch.deliver` (line [40](https://github.com/Agoric/SwingSet/blob/55364f834a64b6aa5dd3728062bc8f61dfe7f0cb/src/kernel/commsSlots/commsSlots.js#L40) of CommsSlots.js) to 1) machineName(s) to send the message to, and 2) the slot that we should use to represent this facetid to each machine. (The same applies to [`notifyFulfillToData` line 136](https://github.com/Agoric/SwingSet/blob/55364f834a64b6aa5dd3728062bc8f61dfe7f0cb/src/kernel/commsSlots/commsSlots.js#L136), [`notifyFulfillToPresence` line 170](https://github.com/Agoric/SwingSet/blob/55364f834a64b6aa5dd3728062bc8f61dfe7f0cb/src/kernel/commsSlots/commsSlots.js#L170), and [`notifyReject` line 193](https://github.com/Agoric/SwingSet/blob/55364f834a64b6aa5dd3728062bc8f61dfe7f0cb/src/kernel/commsSlots/commsSlots.js#L193).) 

At line 40, we do not know where the message should be sent, and in fact, it may be the case that it needs to sent to multiple machines. An example of this case would be a promise that we have told multiple machines about, and now we need to notify these machines that it was resolved. (Does this sound right to you, @warner?)

If this is indeed the requirement, then any data structure that requires us to know the target machine name ahead of time will not work. If this is the requirement, then we will need, in some shape or form, a mapping from one kernelSlot -> a collection of records, each representing the message that should be sent to a single machine. (This collection would be of length 1 if the kernelSlot only maps to one machine.) This is exactly what our current CList implementation does (see the `add` function on [line 112](https://github.com/Agoric/SwingSet/blob/55364f834a64b6aa5dd3728062bc8f61dfe7f0cb/src/kernel/commsSlots/state/CLists.js#L112)). It has one kernelSlot mapped to a map of machineName -> an object representing the message for a machine, including the machineName. 

In the above case, where we do not know the machine name and want to send a message to all machines with an interest in the kernelSlot, it keys on the kernelSlot and turns the map into a list of entries. We then must loop through the list and send the correct message to each machine. I believe this fulfills our requirements and does so efficiently.

If we do know the machine that we are sending a message to, there is an alternative function that keys on the kernelSlot and the machineName to efficiently get the correct message to send to that machine. This is the case for the argument slots in the `dispatch` calls mentioned above. For instance, in `dispatch.deliver` [line 112](https://github.com/Agoric/SwingSet/blob/55364f834a64b6aa5dd3728062bc8f61dfe7f0cb/src/kernel/commsSlots/commsSlots.js#L112) we now know the machine we are sending to, so we use that machineName as a key. This sounds very similar to what you described [here](https://github.com/Agoric/cosmic-swingset/issues/18#issuecomment-500953655), although with a slightly different structure. 

If my understanding of the requirements is correct, then `CLists.js makeCLists() / checkIfAlreadyExists()` correctly uses `&&`. We may already have a kernelSlot, but we may not have the unique pair (kernelSlot, outboundWireMessage) yet. If we used ||, we would not be able to support one kernelSlot mapped to multiple machines, since the || would be true if the kernelSlot already exists. 

If you would like to move to alternative data structure, please let me know, and I can do it. I just want to ensure that we're doing so on accurate information and are on the same page with regards to requirements.

**Comment by warner** [comment]
in the old repo. this was SwingSet issue 79
